---
title: "seascape_outFLANK"
output: html_document
date: "2025-06-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#setwd("~/Desktop/MVP-H2F-HatcheryField")
```

### Packages

```{r}

library(dplyr)
library(bigsnpr)
library(bigstatsr)
library(robustbase)
library(ggplot2)
library(ggrepel)
library(hierfstat)
library(reshape2)
library(adegenet)
library(viridis)
library(pegas)
library(tidyverse)
library(colorspace)
library(OutFLANK)
library(CMplot)

```

### Load data

```{r}

seascape_inds <- readRDS(file.path("..", "..", "data", "parental_genetics_structure", "20250604_samp_full_subset_seascape.rds"))

seascape_full <- readRDS(file.path("..", "..", "data", "parental_genetics_structure", "20250606_FULLSNPs_seascape_labeled.rds"))

seascape_thinned <- readRDS(file.path("..", "..", "data", "parental_genetics_structure", "20250606_THINNEDSNPs_seascape_labeled.rds"))

```

### OutFLANK

#### Data preparation - thinned

``` {r}

# rename for processing
outflank_thinned <- seascape_thinned

# make sample IDs into a real column (instead of rownames)
sample_IDs <- rownames(outflank_thinned)
outflank_thinned$clean_ID <- sample_IDs # "clean_ID" is the column name in samp_full_subset

# reset the rownames to empty
rownames(outflank_thinned) <- NULL

# make sure labels in fst data still line up with sample data
if(!identical((outflank_thinned$clean_ID),seascape_inds$clean_ID)){
    print("Error sample names don't line up")
    break
   } # passes

# store data to check labels 
labels_check <- outflank_thinned$clean_ID
head(labels_check)
samp_labels_check <- seascape_inds$clean_ID
head(samp_labels_check)

# check that labels are still all lined up
identical(labels_check, samp_labels_check) # TRUE

```

```{r}

# add population labels to data
outflank_thinned$ID_SiteDate <- seascape_inds$ID_SiteDate

# move sample and population columns to front 
n_cols <- ncol(outflank_thinned)
outflank_thinned <- outflank_thinned[, c((n_cols-1):n_cols, 1:(n_cols-2))]

# sanity check: number of columns 
dim(outflank_thinned) # number of SNPs (115185) + sample col + pop col = 115187

# check number of samples per population
population_counts <- table(outflank_thinned$ID_SiteDate)
population_counts # no samples missing from any population

```

#### Data preparation - full

``` {r}

# rename for processing
outflank_full <- seascape_full

# make sample IDs into a real column (instead of rownames)
sample_IDs <- rownames(outflank_full)
outflank_full$clean_ID <- sample_IDs # "clean_ID" is the column name in samp_full_subset

# reset the rownames to empty
rownames(outflank_full) <- NULL

# make sure labels in fst data still line up with sample data
if(!identical((outflank_full$clean_ID),seascape_inds$clean_ID)){
    print("Error sample names don't line up")
    break
   } # passes

# store data to check labels 
labels_check <- outflank_full$clean_ID
head(labels_check)
samp_labels_check <- seascape_inds$clean_ID
head(samp_labels_check)

# check that labels are still all lined up
identical(labels_check, samp_labels_check) # TRUE

```

```{r}

# add population labels to data
outflank_full$ID_SiteDate <- seascape_inds$ID_SiteDate

# move sample and population columns to front 
n_cols <- ncol(outflank_full)
outflank_full <- outflank_full[, c((n_cols-1):n_cols, 1:(n_cols-2))]

# sanity check: number of columns 
dim(outflank_full) # number of SNPs (153921) + sample col + pop col = 153923

# check number of samples per population
population_counts <- table(outflank_full$ID_SiteDate)
population_counts # no samples missing from any population

```

```{r}

# remove laguna madre from both
outflank_full <- outflank_full %>%
  filter(ID_SiteDate != "LM_TX_2022-7-10") %>%
  droplevels()

outflank_thinned <- outflank_thinned %>%
  filter(ID_SiteDate != "LM_TX_2022-7-10") %>%
  droplevels()

# convert population to factor
outflank_full$ID_SiteDate <- as.factor(outflank_full$ID_SiteDate)

# check dimensions one more time
dim(outflank_full) # 153923

```

```{r}

# remove sample column
outflank_full <- outflank_full[, -1]

# OutFLANK components: snp matrix, locus names, population names
# documentation: https://github.com/whitlock/OutFLANK/blob/master/OutFLANK%20readme.pdf

# create snp matrix
SNPmat <- as.matrix(outflank_full[,-1])  # snp matrix - exclude the pop column
SNPmat <- apply(SNPmat, 2, as.numeric)  # convert all columns to numeric
SNPmat[is.na(SNPmat)] <- 9  # replace NA with 9 for missing data - there shouldn't be any 9s

# create locus names
locus_names <- colnames(outflank_full)[-1]  # exclude first column (population)

# create pop names
pop_names <- rep(outflank_full$ID_SiteDate, each = nrow(SNPmat) / nrow(outflank_full)) # replicate based on number of rows

pop_counts_outflank <- table(pop_names) # create a table to check with pop counts from before

pop_counts_outflank # these two should match
population_counts # these two should match

# make input data for OutFLANK
FstDataFrame_seascape <- MakeDiploidFSTMat(SNPmat, locus_names, pop_names)

```

#### Data checks

```{r}

# data check: heterozygosity vs. Fst
plot(FstDataFrame_seascape$He, FstDataFrame_seascape$FST) 

# data check: Fst vs. FstNoCorr
plot(FstDataFrame_seascape$FST, FstDataFrame_seascape$FSTNoCorr) # uncorrected Fst is always larger

```

#### Run OutFLANK

```{r}

outflank_thinned <- outflank_thinned %>%
  filter(ID_SiteDate != "LM_TX_2022-7-10") %>%
  droplevels()

outflank_thinned <- outflank_thinned %>%
  select(-1, -2)

# first, run OutFLANK on thinned SNPs
out_trim <- OutFLANK(FstDataFrame_seascape[FstDataFrame_seascape$LocusName %in% colnames(outflank_thinned), ], # using pruned SNPs
                     LeftTrimFraction = 0.05, # defaults
                     RightTrimFraction = 0.05, 
                     Hmin = 0.1, 
                     NumberOfSamples = 39, # number of populations
                     qthreshold = 0.05)

# view results
str(out_trim)
head(out_trim$results)

# check the fit
OutFLANKResultsPlotter(out_trim, withOutliers = TRUE,
                       NoCorr = TRUE, Hmin = 0.1, binwidth = 0.001, Zoom =
                         FALSE, RightZoomFraction = 0.05, titletext = NULL) # looks fine

# zoom in on right tail
OutFLANKResultsPlotter(out_trim , withOutliers = TRUE,
                       NoCorr = TRUE, Hmin = 0.1, binwidth = 0.001, Zoom =
                         TRUE, RightZoomFraction = 0.15, titletext = NULL) # looks fine

# check p value histogram - should look flat (not great)
hist(out_trim$results$pvaluesRightTail)

```

#### Calculate p-values

```{r}

# then, calulate p-values on the full set
P1 <- pOutlierFinderChiSqNoCorr(FstDataFrame_seascape, Fstbar = out_trim$FSTNoCorrbar, 
                                   dfInferred = out_trim$dfInferred, qthreshold = 0.05, Hmin=0.05)

# view data
head(P1)
tail(P1)

# look for outliers - highlighted in blue
my_out <- P1$OutlierFlag==TRUE
plot(P1$He, P1$FST, pch=19, col=rgb(0,0,0,0.1))
points(P1$He[my_out], P1$FST[my_out], col="blue")

# check the p-value histogram for the full set of data
# if there are outliers, it should look flat with an inflation near 0
hist(P1$pvaluesRightTail)

```

#### Data product: OutFLANK results, SNP info

```{r}

# separating by chromosome
a = sprintf("%08d", muts_outflank$Position)
muts_outflank$chrom_position <- paste(muts_outflank$Chromosome, a, sep = ".")

# add chromosome positions to dataframe
P1$Affx.ID <- P1$LocusName
joined_P1 <- left_join(P1, muts_outflank, by = c("Affx.ID" = "Affx.ID"))

write_csv(joined_P1, file.path("..", "..", "data", "putative_selection", "outflank_results.csv"))

```
