---
title: "CviMVP_Nursery_Hatchery_Analysis"
output: pdf_document
date: "2024-02-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#load necessary packages
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(multcompView)
library(car) #upload package with Anova function
library(cowplot)
```

#Set working directory
```{r}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

```{r}
#download data in csv format

#download spawn treatment data
spawn <- read.csv("../../data/performance_H2F/CviMVP_Larvae_Growth-spawn_trt.csv")
#download group data
group <- read.csv("../../data/performance_H2F/CviMVP_Larvae_Growth-group.csv")
#download larvae image length data
larvae_img <- read.csv("../../data/performance_H2F/CviMVP_Larvae_Growth-larvae_img.csv")
```

```{r}
#make mega sheet with all length data

#join image data to group data in new dataframe

len_df <-group %>%
          left_join(larvae_img, by = "Group_Day_Key")

#remove some columns
len_analysis_df <- subset(len_df, select = -c(Ind_ID, Group_Day_Label.y, Image_Key, Img_Notes,SpawnTrt_Key, Filter_size_µm, Sample_count, Group_count, Vial_label, Notes, Survival_rate_perc, Image_num, Num_Larvae_in_img, Hinge_Length_µm, Tank))

#rename columns

```

```{r}
#subset data for oysters aged 15-78 days (later stage offspring)
latestage_df <- subset(len_analysis_df, Day_analysis == "78"| Day_analysis == "15-21")

#a sample marked WV is erroneously in this data set- remove
latestage_df <- subset(latestage_df, Image_Label != "WV_06_200L_6")

#rename cols
colnames(latestage_df) <- c("site_name", "site_day_key", "site_day_label", "day_trt", "day_an", "day", "date", "image_label", "shell_length_um")

#make column with measurements in millimeters instead of microns
latestage_df$shell_length_mm <- (latestage_df$shell_length_um)/1000
head(latestage_df)
```

```{r}
#prep data for ANOVA

#use grep function to make a vector of all indices in latestage_len with the phrase "small" in them, ignore.case=TRUE means query is not case sensitive. Samples marked "small" were collected at the same time as eyed stage oysters between days 15-21, and these "small" samples never developed to the eyed stage.
small <- grep("small", latestage_df$site_day_label, ignore.case = TRUE)

small_img <- grep("small", latestage_df$image_label, ignore.case = TRUE)

#make new dataframe WITHOUT any indices saved in small, mean remaining data are everything except small larvae
no_small_df <- latestage_df[-small, ]
no_small_df <- latestage_df[-small_img, ]

#rename rows
colnames(no_small_df) <- c("site_name", "site_day_key", "site_day_label", "day_trt", "day_an", "day", "date", "image_label", "shell_length_um", "shell_length_mm")

#exclude "MVP" from site names and include wild or selection line label
no_small_df["site_name"][no_small_df["site_name"] == "MVP-TX"] <- "W1-TX"
no_small_df["site_name"][no_small_df["site_name"] == "MVP-LA"] <- "W2-LA"
no_small_df["site_name"][no_small_df["site_name"] == "MVP-FL"] <- "W3-FL"
no_small_df["site_name"][no_small_df["site_name"] == "MVP-LOLA"] <- "S1-LOLA"
no_small_df["site_name"][no_small_df["site_name"] == "MVP-DEBY"] <- "S2-DEBY"
no_small_df["site_name"][no_small_df["site_name"] == "MVP-JR"] <- "W4-VA"
no_small_df["site_name"][no_small_df["site_name"] == "MVP-NH"] <- "W5-NH"
no_small_df["site_name"][no_small_df["site_name"] == "MVP-ME"] <- "W6-ME"
no_small_df["site_name"][no_small_df["site_name"] == "MVP-LARMIX"] <- "H1-LARMIX"


no_small_df <- no_small_df %>% 
  mutate(site_name = site_name %>% 
           fct_relevel("W1-TX", "W2-LA", "W3-FL", "S1-LOLA", "S2-DEBY", "W4-VA", "W5-NH", "W6-ME", "H1-LARMIX"))

#save latestage_df as a csv file for future analyses
write.csv(no_small_df, "../../data/performance_H2F/latestage_length.csv")

```


```{r}
#calculate mean oyster length per site_name per day using aggregate

#make standard error equation
se <- function(x){
  sd(x)/sqrt(length(x))
}

#find mean lengths of each site_name on each day
means_mm <- aggregate(shell_length_mm ~ site_name + day_an, FUN = mean, data = no_small_df)
colnames(means_mm) <- c("site_name", "days", "mean_length_mm")

#find standard error of length of each site_name on each day
se_mm <- aggregate(shell_length_mm ~ site_name + day_an, FUN = se, data = no_small_df)
colnames(se_mm) <- c("site_name", "days", "se_length_mm")
```

```{r}
#Check if late stage oyster data (day 19 onward, small oysters excluded) match assumptions of ANOVA

len.lm <- lm(shell_length_mm ~ day_an*site_name, data = no_small_df) #fit to lm
len.lm.resid <- len.lm$residuals #save residuals
shapiro.test(len.lm.resid) #use Shapiro Wilk test to assess normality. p <2.2e-16, data is not normal

#plot(len.lm)
#normality is off, definite funnel in homoscedasticity plots, but KEL said to expect that what with the range of values in this data between ages.

#log10 transformation lm
loglen.lm <- lm(log10(shell_length_mm) ~ day_an*site_name, data = no_small_df)
loglen.lm.resid <- loglen.lm$residuals
shapiro.test(loglen.lm.resid)#p < 2.2e-16, no change in normality

#plot(loglen.lm)
# I'm planning to use the log10 transformed data for the analysis, transformations helped get rid of some of the funneling of homoscedasticity, normality is still off, but it's not much different from non-transformed data. No outliers in either model.

#run ANOVA on log transformed length data
no_small_df$loglen <- log10(no_small_df$shell_length_mm)

len.anova3 <- Anova(lm(loglen ~ day_an*site_name, data = no_small_df), type = 3)

len.anova3
#significant interactive effect of site_name and age (p < 2e-16), but no significant effect of site_name on its own (0.1978)

all_pval <- len.anova3$`Pr(>F)`
all_pval <- na.omit(all_pval)
```

#Interaction plot for length as a function of day*
```{r}
no_small_df <- no_small_df %>% 
  arrange(factor(site_name, levels = c("W1-TX", "W2-LA", "W3-FL", "S1-LOLA", "S2-DEBY", "W4-VA", "W5-NH", "W6-ME", "H1-LARMIX")))

ggplot(no_small_df, aes(day_an, loglen, site_name = site_name))+
  #geom_point(data = means_mm, aes(days, log10(mean_length_mm), color = site_name))+
  geom_smooth(method = "lm", se = F, linewidth = .5, aes(color = site_name))+
  theme_bw()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  xlab("Day")+
  ylab("Log10 Transformed Shell Length")+
  ggtitle("Shell Length Across Groups in the Nursery and Hatchery")+
  scale_color_manual(values= c("#3e4989", "#31688e", "#26828e","#440154","#482878", "#1f9e89", "#35b779", "#6ece58", "#fde725"))
```

```{r subset_ages}
#convert site_name and day from chr to factor
no_small_df$site_name <- as.factor(no_small_df$site_name)
no_small_df$day_an <- as.factor(no_small_df$day_an)
str(no_small_df)

#subsetting based on oyster age (days) for oysters on day 78 (end of hatchery stage, pre field deployment (pre-dep))
predep <- subset(no_small_df, day_an == "78")
```

##ANOVA for end of hatchery (day 78) shell lengths only
```{r}
#Linera model and ANOVA for predep shell lengths
predep$site_name <- as.factor(predep$site_name)

predep.lm <- lm(shell_length_mm ~ site_name, data = predep) #fit to lm

predep.lm.resid <- predep.lm$residuals #save residuals

shapiro.test(predep.lm.resid) #use Shapiro Wilk test to assess normality
# p = 0.08176, fail to reject H0, data are normal

#plots to assess if data meet assumptions of 2-way ANOVA
#plot(predep.lm)

#this data looks good, normal, homoscedastic, no outliers

#I should use Anova function to have control over the sum of squares type, but Tukey Kramer test won't run on an Anova object, only aov. Both functions produce the same p-value, so I am going to stick with the aov function for the TK test.

#Tukey-Kramer labels only allow one - per comparison label, so I will replace the - with _
predep$site_name <- gsub("-", "_", predep$site_name)

predep.anova3 <- Anova(lm(shell_length_mm ~ site_name, data = predep))
predep.anova3

predep.anova <- aov(lm(shell_length_mm ~ site_name, data = predep))
summary(predep.anova) 

#extract p-value
predep_pval <- summary(predep.anova)[[1]][["Pr(>F)"]][1]
print(predep_pval)

#post-hoc comparison- Tukey-Kramer test
predep.tuk <- TukeyHSD(x=predep.anova,conf.level = 0.95)

#extract significant letters from TK test and store
require(multcompView)

predep_cld <- multcompLetters4(predep.anova, predep.tuk)

predep_dt <- group_by(predep, site_name) %>%
  summarise(m=mean(shell_length_mm)) %>%
  arrange(desc(m))

predep_cld <- as.data.frame.list(predep_cld$site_name)
predep_dt$predep_cld <- predep_cld$Letters

#make shell length numeric in predep
predep$shell_length_mm <- as.numeric(predep$shell_length_mm)
```

#P Adjust
```{r p_adjust}
#adjust p-value to correct for multiple tests. Make vector of p-values from each ANOVA
p_values <- c(all_pval, predep_pval)

p_values

p_adj <- p.adjust(p_values, method = "BH")

p_adj

```


```{r predep_boxplot}
predep <- predep %>% 
  mutate(site_name = site_name %>% 
           fct_relevel("W1_TX", "W2_LA", "W3_FL", "S1_LOLA", "S2_DEBY", "W4_VA", "W5_NH", "W6_ME", "H1_LARMIX"))

#plot. fatten = NULL will remove the median lines in each box, allowing me to display the mean instead. Making fatten = NULL will result in warning messages, but that's ok.
predep_box <- ggplot(data = predep, aes(site_name, shell_length_mm))+
  geom_boxplot(color = c("#3e4989", "#31688e", "#26828e","#440154","#482878", "#1f9e89", "#35b779", "#6ece58", "#fde725"), fill = c("#3e4989", "#31688e", "#26828e","#440154","#482878", "#1f9e89", "#35b779", "#6ece58", "#fde725"), linewidth = .2, fatten = NULL)+
    scale_x_discrete(name = "Broodstock Group", limits = c("W1_TX", "W2_LA","W3_FL", "S1_LOLA", "S2_DEBY", "W4_VA", "W5_NH", "W6_ME", "H1_LARMIX"), labels = c("W1-TX","W2-LA","W3-FL", "S1-LOLA", "S2-DEBY", "W4-VA", "W5-NH", "W6-ME", "H1-LARMIX"))+
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2, linewidth = .4, color = c("white", "white", "white", "white", "white", "black", "black", "black", "black"))+
  stat_summary(fun = mean, geom = "errorbar", aes(ymax = ..y.., ymin = ..y..), width = 0.75, size = .4, linetype = "solid", color = c("white", "white", "white", "white", "white", "black", "black", "black", "black"))+
  ylab("Day 78 Shell Length (mm)")+
  xlab("Broodstock Group")+
  labs(subtitle = "p < 0.001")+
  ylim(c(0,32))+
  geom_text(data = predep_dt, size = 3, aes(label = predep_cld, y = 29, x = site_name), vjust = -0.5)+
  ggtitle("Pre-Field-Deployment (Day 78) Shell Lengths")+
  theme_bw()+
  theme(plot.subtitle = element_text(size = 9), axis.title.y = element_text(size = 11), axis.title.x = element_text(size = 11), panel.grid.major = element_blank(), panel.grid.minor = element_blank())

predep_box
```

