---
title: "NM_Condition_Survival_Figs"
author: "Nicole Mongillo"
date: "2025-06-02"
output: pdf_document
---

Condition plots created from code developed by Zea Segnitz.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load libraries
```{r}
library(fitdistrplus)
library(dplyr)
library(lme4)
library(lmerTest)
library(pbkrtest)
library(emmeans)
library(multcompView)
library(multcomp)
library(tidyverse)
library(lme4) 
library(effects)
library(ggsignif) 
library(renv)
library(readr)
```

```{r}
setwd("~/Desktop/GitHub/MVP-H2F-HatcheryField/src/parent_effects_H2F")
```

### Data preparation
```{r}
# load in dataset 
MVP_phenotyping_final <- read_csv("../../data/condition_index_H2F/MVP_phenotyping_final.csv", show_col_types = FALSE)

# put the populations in correct factor order
MVP_phenotyping_final$population <- factor(MVP_phenotyping_final$population, levels = c("W1-TX", "W2-LA", "W3-FL", "S1-LOLA", "S2-DEBY", "W4-VA", "W5-NH", "W6-ME", "H1-LARMIX","H2-SEEDMIX"))

population_colors <- c(
  "W1-TX" = "#3e4989",
  "W2-LA" = "#31688e",
  "W3-FL" = "#26828e",
  "W4-VA" = "#1f9e89",
  "S1-LOLA" = "#440154",
  "S2-DEBY" = "#482878",
  "W5-NH" = "#35b779",
  "W6-ME" = "#6ece58",
  "H1-LARMIX" = "#fde725",
  "H2-SEEDMIX"= "#b5de2b")

#subset the timepoints 
data202405 = MVP_phenotyping_final %>% filter(samplingTimePoint == "2024-05")
data202411 = MVP_phenotyping_final %>% filter(samplingTimePoint == "2024-11")

#set the levels 
data202405$population <- factor(data202405$population, levels = c("W1-TX", "W2-LA", "W3-FL", "W4-VA", "S1-LOLA", "S2-DEBY", "W5-NH", "W6-ME", "H1-LARMIX", "H2-SEEDMIX"))

data202411$population <- factor(data202411$population, levels = c("W1-TX", "W2-LA", "W3-FL", "W4-VA", "S1-LOLA", "S2-DEBY",  "W5-NH", "W6-ME", "H1-LARMIX", "H2-SEEDMIX"))
```

### Create linear mixed-effects models 
```{r}
mixed.model.3 <- lmer(CI ~ site*population + (1 | bagID), data = data202411)
mixed.model.3.site.pop = lmer(CI ~ site.pop + (1 | bagID), data = data202411) # build this as well to be able to compute pairwise differences between every site.pop combination 
```

post-hoc testing. Use emmeans to find and pairwise compare means of every population. 
```{r}
#pairwise comparisons of every site-population combination ex. LEW.TX etc. - only for Nov 2024 because site is not significant at May 2024
mm3.site.pop.emmeans = emmeans(mixed.model.3.site.pop, pairwise ~ site.pop, adjust = "tukey")

# get just the emmeans output 
mm3.emm = mm3.site.pop.emmeans$emmeans

# Generate compact letter display
mm3.cld_letters <- cld(mm3.emm, adjust = "tukey", Letters = letters)

#make sure the letters are in dataframes
as.data.frame(mm3.cld_letters)

#add cols for site and parental group separately based on those in data202411
site_pop <- subset(data202411, select = c("site.pop", "site", "population"))
site_pop1 <- site_pop %>% 
  distinct(site.pop, .keep_all = TRUE)

mm3.cld_letters1 <- left_join(mm3.cld_letters, site_pop1, by = "site.pop")
```

### Model with time inclusion
```{r}
mixed.model.4 = lmer(CI ~ site*population*samplingTimePoint + (1 | bagID), data = MVP_phenotyping_final %>% filter(samplingTimePoint == "2024-05" | samplingTimePoint == "2024-11"))
anova(mixed.model.4)
step(mixed.model.4)
### confirms that current model is the best one 
```

### Plot the data 
This creates boxplots of the condition index by population, with unique colors for LEW and YR. 
```{r}
# Nov 2024
field_ci <- ggplot(data202411, aes(x = population, y = CI, fill = site)) +
  geom_boxplot(position = position_dodge(width = 0.8)) +  
  scale_x_discrete() +  
  labs(x = "Parental Group", y = "Condition Index", title = "Condition Index vs. Parental Group", subtitle = "Final Field Time Point", fill = "Site") +   scale_fill_manual(values = c("LEW" = "#FFC107", "YR" = "#025BA9"), labels = c("LEW" = "Lewisetta", "YR" = "York River")) +  
  theme_minimal() +
  geom_text(data = mm3.cld_letters1, aes(label = .group, x = population, y = emmean+10*SE), size = 3, angle = 60, position=position_dodge(width=1))+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, color = "black", size = 10),
        axis.title = element_text(size = 12),
        axis.text.y = element_text(color = "black", size = 10),
        legend.text = element_text(size = 10),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

field_ci

ggsave("field_ci.pdf",
       plot = field_ci,
       device = "pdf",
       path = "../../figures/performance_H2F",
       height = 4,
       width = 6)
```