---
title: "CI_survival"
author: "Nicole Mongillo"
date: "2025-05-05"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(emmeans)
library(tidyverse)
library(car)
library(ggplot2)
library(gridExtra)
library(multcompView) #extract significance letters from Tukey-Kramer test
library(cowplot) #arrange ggplots
library(ggpmisc)
```

### Set working directory
```{r}
setwd("~/Desktop/GitHub/MVP-H2F-HatcheryField/src/condition_index_analysis_H2F")
```

### Load data
```{r}
#Condition index data
condition <- read.csv("../../data/condition_index_H2F/MVP_phenotyping_final.csv")

#Field survival data
survival <- read.csv("../../data/performance_H2F/mortality_bags_022025.csv")
```

### Prepare data for ANCOVA
```{r}
#subset survival data to only include relevant columns
surv_sub <- survival[, c(2,3,5,6,10)]

#rename columns to match names in condition df
colnames(surv_sub) <- c("population", "bagID", "bag_site", "SpawnTrt_Key", "survival")

#subset condition data to only include final time point (Nov. 2024)
condition_sub <- condition %>% 
  filter(samplingTimePoint == "2024-11") %>% 
  select(c(1,2,19,21,22,23))

#paste "MVP" at the start of all bagIDs in condition_sub to match format in surv_sub
condition_sub$bagID <- paste("MVP", condition_sub$bagID, sep = "-")

#calculate mean condition in each bag and save to new object
mean_CI <- aggregate(CI ~ bagID, data = condition_sub, FUN = mean)

#2 bags are missing from the survival data, remove those bags from mean_CI for now
mean_CI_sub <- mean_CI[mean_CI$bagID %in% surv_sub$bags_label, ]

#rename rows
colnames(mean_CI_sub) <- c("bagID", "mean_CI")

#merge survival and mean CI data
CI_surv <- left_join(surv_sub, mean_CI_sub, by = "bagID")
```

### Run ANCOVA
```{r}
#run linear model
CI_surv_lm <- lm(mean_CI ~ survival*bag_site, data = CI_surv)
#save residuals
CI_surv_resid <- CI_surv_lm$residuals
#assess normality with Shapiro-Wilk test
shapiro.test(CI_surv_resid) #p = 0.295, residuals are normal
plot(CI_surv_lm) 

CI_surv_ancova <- Anova(CI_surv_lm, type = 3)

CI_surv_ancova
#survival p = 0.657, bag_site p = 0.000817, interaction p = 0.0967
```
