---
title: "CviMVP_Nursery_Hatchery_Analysis"
output: pdf_document
date: "2024-02-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#load necessary packages
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(multcompView)
library(car) #upload package with Anova function
library(cowplot)
```

```{r}
#download data in csv format and view it

#download spawn treatment data
spawn <- read.csv("/Users/nicolemongillo/Desktop/GitHub/MVP_Chesapeake_VIMS_hatchery/data/CviMVP_Larvae_Growth-spawn_trt.csv")
#Examine data
spawn
summary(spawn)

#download group data
group <- read.csv("/Users/nicolemongillo/Desktop/GitHub/MVP_Chesapeake_VIMS_hatchery/data/CviMVP_Larvae_Growth-group.csv")
summary(group)

#download larvae image length data
larvae_img <- read.csv("/Users/nicolemongillo/Desktop/GitHub/MVP_Chesapeake_VIMS_hatchery/data/CviMVP_Larvae_Growth-larvae_img.csv")
summary(larvae_img)
```

```{r}
#make mega sheet with all length data

#join image data to group data in new dataframe

len_df <-group %>%
          left_join(larvae_img, by = "Group_Day_Key")

#remove some columns
len_analysis_df <- subset(len_df, select = -c(Ind_ID, Group_Day_Label.y, Image_Key, Img_Notes,SpawnTrt_Key, Filter_size_µm, Sample_count, Group_count, Vial_label, Notes, Survival_rate_perc, Image_num, Num_Larvae_in_img, Hinge_Length_µm, Tank))

```

```{r}
#subset late stage oyster data (days19-78)
latestage_df <- subset(len_analysis_df, Day_analysis == "49"| Day_analysis == "78"| Day_analysis == "15-21")

#a sample marked WV is erroneously in this data set- remove
latestage_df <- subset(latestage_df, Image_Label != "WV_06_200L_6")

#rename cols
colnames(latestage_df) <- c("group", "group_day_key", "group_day_label", "day_trt", "day_an", "day", "date", "image_label", "shell_length_um")

latestage_df$shell_length_mm <- (latestage_df$shell_length_um)/1000

head(latestage_df)

#preliminary exploration of data
summary(latestage_df)
```

```{r}
#prep data for ANOVA

#use grep function to make a vector of all indices in latestage_len with the phrase "small" in them, ignore.case=TRUE means query is not case sensitive. Samples marked "small" were collected at the same time as eyed stage oysters between days 15-21, and these "small" samples never developed to the eyed stage.
small <- grep("small", latestage_df$group_day_label, ignore.case = TRUE)

small_img <- grep("small", latestage_df$image_label, ignore.case = TRUE)

#make new dataframe WITHOUT any indices saved in small, mean remaining data are everything except small larvae
no_small_df <- latestage_df[-small, ]
no_small_df <- latestage_df[-small_img, ]

#rename rows
colnames(no_small_df) <- c("group", "group_day_key", "group_day_label", "day_trt", "day_an", "day", "date", "image_label", "shell_length_um", "shell_length_mm")

#exclude "MVP" from group names to shorten them
no_small_df["group"][no_small_df["group"] == "MVP-DEBY"] <- "DEBY"
no_small_df["group"][no_small_df["group"] == "MVP-FL"] <- "FL"
no_small_df["group"][no_small_df["group"] == "MVP-JR"] <- "JR"
no_small_df["group"][no_small_df["group"] == "MVP-LA"] <- "LA"
no_small_df["group"][no_small_df["group"] == "MVP-LARMIX"] <- "LARMIX"
no_small_df["group"][no_small_df["group"] == "MVP-LOLA"] <- "LOLA"
no_small_df["group"][no_small_df["group"] == "MVP-ME"] <- "ME"
no_small_df["group"][no_small_df["group"] == "MVP-NH"] <- "NH"
no_small_df["group"][no_small_df["group"] == "MVP-TX"] <- "TX"

no_small_df <- no_small_df %>% 
  mutate(group = group %>% 
           fct_relevel("DEBY", "LOLA", "JR", "TX", "LA", "FL", "NH", "ME", "LARMIX"))

#save latestage_df as a csv file for future analyses
write.csv(no_small_df, "/Users/nicolemongillo/Desktop/GitHub/MVP_Chesapeake_VIMS_hatchery/data/latestage_length.csv")

```


```{r}
#calculate mean oyster length per group per day using aggregate

#make standard error equation
se <- function(x){
  sd(x)/sqrt(length(x))
}

#find mean lengths of each group on each day
means_mm <- aggregate(shell_length_mm ~ group + day_an, FUN = mean, data = no_small_df)
colnames(means_mm) <- c("group", "days", "mean_length_mm")

#find standard error of length of each group on each day
se_mm <- aggregate(shell_length_mm ~ group + day_an, FUN = se, data = no_small_df)
colnames(se_mm) <- c("group", "days", "se_length_mm")
```

```{r}
#Check if late stage oyster data (day 19 onward, small oysters excluded) match assumptions of ANOVA

len.lm <- lm(shell_length_mm ~ day_an + group, data = no_small_df) #fit to lm

len.lm.resid <- len.lm$residuals #save residuals

shapiro.test(len.lm.resid) #use Shapiro Wilk test to assess normality

#plots to assess if data meet assumptions of ANOVA
par(mfrow = c(1,1))

#plot(len.lm)
#normality is a bit off, definite funnel in homoscedasticity plots, but KEL said to expect that what with the range of values in this data between ages

#log10 transformation lm
loglen.lm <- lm(log(shell_length_mm) ~ day_an + group, data = no_small_df)
loglen.lm.resid <- loglen.lm$residuals

#plot(loglen.lm)
# I'm planning to use the log10 transformed data for the analysis, transformations helped get rid of some of the funneling of homoscedasticity, normality is still a bit off, but it's not much different from non-transformed data. No outliers in either model

#run ANOVA on log transformed length data
no_small_df$log10len <- log10(no_small_df$shell_length_mm)

len.anova3 <- Anova(lm(log10len ~ day_an + group + day_an:group, data = no_small_df), type = 3)

len.anova3

summary(len.anova3)

all_pval <- len.anova3$`Pr(>F)`

all_pval <- na.omit(all_pval)

#significant interactive effect of group and age (p < 2e-16), but no significant effect of group on its own (0.4428)

```

```{r subset_ages}
#convert group and day from chr to factor
no_small_df$group <- as.factor(no_small_df$group)
no_small_df$day_an <- as.factor(no_small_df$day_an)
str(no_small_df)

#subsetting based on oyster age (days)
eyed <- subset(no_small_df, day_an == "15-21")
seed <- subset(no_small_df, day_an == "49")
predep <- subset(no_small_df, day_an == "78")

#make barplots of shell length vs group for each age/day

#barplot of shell length distributions pooled across all days
bp_all <- boxplot(no_small_df$shell_length_mm ~ no_small_df$group,
        main = "Shell Length Distribution In Each Group Days 19-78",
        xlab = "Group Label",
        ylab = "Shell Length mm")
#seed larvae shell length vs group
bp_seed <- boxplot(seed$shell_length_mm ~ seed$group,
        main = "Seed Larvae (Day 49) Shell Length",
        xlab = "Group Label",
        ylab = "Shell Length (mm)",
        ylim = c(0, 10))
```

#Eyed ANOVA and Post-Hoc Comparison
```{r}
#I want to run ANOVAs comparing shell length to group for each day separately

#ANOVA for eyed shell lengths
eyed$group <- as.factor(eyed$group)

eyed.lm <- lm(shell_length_mm ~ group, data = eyed) #fit to lm

eyed.lm.resid <- eyed.lm$residuals #save residuals

shapiro.test(eyed.lm.resid) #use Shapiro Wilk test to assess normality, p < 1.78 e-09,so not normal

#plots to assess if data meet assumptions of ANOVA

#plot(eyed.lm)
#normality is a bit off, check log10 transformed lengths

#log10 transformation lm
logeyed.lm <- lm(log(shell_length_mm) ~ group, data = eyed)
logeyed.lm.resid <- logeyed.lm$residuals


#plot(logeyed.lm)

#no real change in normality between transformed and non-transformed data, no outliers and homoscedastic data regardless, so I am going to do this with non transformed data


#run ANOVA on non transformed length data
eyed.anova3 <- Anova(lm(shell_length_mm ~ group, data = eyed), type = 3)
eyed.anova3 #p <2e-16, same as with other aov function

eyed.anova <- aov(lm(shell_length_mm ~ group, data = eyed))
eyed_anova_result <- as.matrix(summary(eyed.anova)) #significant p-value, p <2e-16

eyed_pval <- summary(eyed.anova)[[1]][["Pr(>F)"]][1]
print(eyed_pval)

#post-hoc comparison- Tukey-Kramer test
eyed.tuk <- TukeyHSD(x=eyed.anova,conf.level = 0.95)

par(mfrow = c(1,1))

plot(eyed.tuk)
require(multcompView)

eyed_cld <- multcompLetters4(eyed.anova, eyed.tuk)

eyed_dt <- group_by(eyed, group) %>%
  summarise(m=mean(shell_length_mm)) %>%
  arrange(desc(m))

eyed_cld <- as.data.frame.list(eyed_cld$group)
eyed_dt$eyed_cld <- eyed_cld$Letters
```

##ANOVA for pre-deployment (day 78) shell lengths only
```{r}
#Linera model and ANOVA for predep shell lengths
predep$group <- as.factor(predep$group)

predep.lm <- lm(shell_length_mm ~ group, data = predep) #fit to lm

predep.lm.resid <- predep.lm$residuals #save residuals

shapiro.test(predep.lm.resid) #use Shapiro Wilk test to assess normality
# p = 0.08176, fail to reject H0, data are normal

#plots to assess if data meet assumptions of 2-way ANOVA

#plot(predep.lm)

#this data looks good, normal, homoscedastic, no outliers

#I should use Anova function, but Tukey Kramer test won't run on an Anova object, only aov. Both functions produce the same p-value, so I am going to stick with the aov function for the TK test.
predep.anova3 <- Anova(lm(shell_length_mm ~ group, data = predep))
predep.anova3

predep.anova <- aov(lm(shell_length_mm ~ group, data = predep))
summary(predep.anova) 

#extract p-value
predep_pval <- summary(predep.anova)[[1]][["Pr(>F)"]][1]
print(predep_pval)

#post-hoc comparison- Tukey-Kramer test
predep.tuk <- TukeyHSD(x=predep.anova,conf.level = 0.95)

#extract significant letters from TK test and store
require(multcompView)

predep_cld <- multcompLetters4(predep.anova, predep.tuk)

predep_dt <- group_by(predep, group) %>%
  summarise(m=mean(shell_length_mm)) %>%
  arrange(desc(m))

predep_cld <- as.data.frame.list(predep_cld$group)
predep_dt$predep_cld <- predep_cld$Letters

#make shell length numeric in predep
predep$shell_length_mm <- as.numeric(predep$shell_length_mm)
```

#P Adjust
```{r p_adjust}
#adjust p-value to correct for multiple tests. Make vector of p-values from each ANOVA
p_values <- c(all_pval, eyed_pval, predep_pval)

p_values

p_adj <- p.adjust(p_values, method = "BH")

p_adj
```


```{r 2panel_plot}
eyed_box <- ggplot(data = eyed, aes(group, shell_length_mm))+
  geom_boxplot(size = .2)+
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2, linewidth = .2, color = "red")+
  ggtitle("Oyster Shell Lengths at Days 15-21 and Day 78 Across Broodstock Groups")+
  ylab("Days 15-21 Shell Length (mm)")+
  xlab("Broodstock Group")+
  ylim(c(0.2,.4))+
  geom_text(data = eyed_dt, size = 3, aes(label = eyed_cld, y = .35), vjust = -0.5)+
  labs(subtitle = "A: p < 0.001")+
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), title = element_text(size = 9),  plot.subtitle = element_text(size = 9), axis.title.y = element_text(size = 8), axis.title.x = element_blank())

eyed_box

#plot
predep_box <- ggplot(data = predep, aes(group, shell_length_mm))+
  geom_boxplot(size = .2)+
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2, linewidth = .2, color = "red")+
  ylab("Day 78 Shell Length (mm)")+
  xlab("Broodstock Group")+
  labs(subtitle = "B: p < 0.001")+
  ylim(c(0,32))+
  geom_text(data = predep_dt, size = 3, aes(label = predep_cld, y = 29, x = group), vjust = -0.5)+
  theme(plot.title = element_blank(), plot.subtitle = element_text(size = 9), axis.title.y = element_text(size = 8), axis.title.x = element_text(size = 8))

predep_box

plot_grid(eyed_box, predep_box, ncol = 1, align = "v")
```

